[package]
name = "toy_jvm"
version = "0.1.0"
authors = ["sh1nduu <sh1nduu@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
